
build : bin/
	gcc -std=gnu90 src/r.c src/projectLib.c -o bin/r
	gcc -std=gnu90 src/q.c src/projectLib.c -o bin/q
	gcc -std=gnu90 src/p.c src/projectLib.c -o bin/p
	gcc -std=gnu90 src/c.c src/projectLib.c -o bin/c
	gcc -std=gnu90 src/m.c src/projectLib.c -o bin/m

bin :
	mkdir bin

help :	
	cat README
